// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-comparison/NoPhoto.tsx": () => import("../components/mockups/hero-comparison/NoPhoto.tsx"),
  "./components/mockups/hero-comparison/WithPhoto.tsx": () => import("../components/mockups/hero-comparison/WithPhoto.tsx")
};
